---
include:
  - board: nice_nano_v2
    shield: q10_dongle dongle_display
    snippet: studio-rpc-usb-uart
  - board: zitaotech_q10

  # Flash these once to clear saved Bluetooth/settings data.
  - board: nice_nano_v2
    shield: settings_reset
  - board: zitaotech_q10
    shield: settings_reset
