---
include:
  - board: xiao_ble
    shield: q10_dongle dongle_display
  - board: zitaotech_q10

  # Flash these once to clear saved Bluetooth/settings data.
  - board: xiao_ble
    shield: settings_reset
  - board: zitaotech_q10
    shield: settings_reset
